### PR TITLE
Close #279: Report back user errors to client without crashing the server

### LINKED ISSUE #279: voltron proxy does not redirect exceptions to clients
use case: try to do a management call to a client that is no more connected to the server.

server crashes.

on server:

```
org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: Runtime exception in deserializer
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:497)
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$2(ManagedEntityImpl.java:308)
	at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:1025)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:173)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:164)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23)
	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)
Caused by: java.lang.RuntimeException: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: Runtime exception in deserializer
	at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:724)
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:472)
	... 8 more
Caused by: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: Runtime exception in deserializer
	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:388)
	at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:717)
	... 9 more
Caused by: org.terracotta.entity.MessageCodecException: Runtime exception in deserializer
	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:387)
	... 10 more
Caused by: java.lang.IllegalStateException: Client 81279@127.0.0.1:Ehcache:SEFormy-cm-name-2:2b72ff6c02ff43e29246443ba635324a is either not found or not manageable
	at org.terracotta.management.service.monitoring.DefaultManagementService.lambda$sendManagementCallRequest$0(DefaultManagementService.java:105)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.terracotta.management.service.monitoring.DefaultManagementService.sendManagementCallRequest(DefaultManagementService.java:105)
	at org.terracotta.management.entity.tms.server.ActiveTmsAgent.call(ActiveTmsAgent.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.terracotta.voltron.proxy.MethodDescriptor.invoke(MethodDescriptor.java:144)
	at org.terracotta.voltron.proxy.ProxyEntityMessage.invoke(ProxyEntityMessage.java:67)
	at org.terracotta.voltron.proxy.server.ProxyInvoker.invoke(ProxyInvoker.java:50)
	at org.terracotta.voltron.proxy.server.ActiveProxiedServerEntity.invoke(ActiveProxiedServerEntity.java:53)
	at org.terracotta.voltron.proxy.server.ActiveProxiedServerEntity.invoke(ActiveProxiedServerEntity.java:30)
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$performAction$9(ManagedEntityImpl.java:717)
	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:382)
	... 10 more
com.tc.exception.TCRuntimeException: Uncaught exception in stage
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:211)
Caused by: java.lang.RuntimeException: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: Runtime exception in deserializer
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:499)
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$2(ManagedEntityImpl.java:308)
	at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:1025)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:173)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:164)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23)
	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)
Caused by: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: Runtime exception in deserializer
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:497)
	... 8 more
Caused by: java.lang.RuntimeException: org.terracotta.exception.EntityUserException: En
```

on client:

```
Caused by: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: org.terracotta.entity.MessageCodecException: Runtime exception in deserializer
	at com.tc.object.InFlightMessage.getWithTimeout(InFlightMessage.java:178) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.object.InFlightMessage.getWithTimeout(InFlightMessage.java:43) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.getWithTimeout(EntityClientEndpointImpl.java:173) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.getWithTimeout(EntityClientEndpointImpl.java:155) ~[client-runtime-5.2.0-pre13.jar:na]
	at org.terracotta.voltron.proxy.client.VoltronProxyInvocationHandler$ProxiedInvokeFuture.get(VoltronProxyInvocationHandler.java:199) ~[management-client-5.2.0-pre15.jar:na]
	at org.terracotta.management.entity.tms.client.DefaultTmsAgentService.get(DefaultTmsAgentService.java:153) ~[management-client-5.2.0-pre15.jar:na]
	at org.terracotta.management.entity.tms.client.DefaultTmsAgentService.call(DefaultTmsAgentService.java:121) ~[management-client-5.2.0-pre15.jar:na]
	at com.terracottatech.management.voltron.VoltronTmsConnection.doCall(VoltronTmsConnection.java:120) ~[classes/:na]
	... 44 common frames omitted
Caused by: org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:MyCluster exception in user code: org.terracotta.entity.MessageCodecException: Runtime exception in deserializer
	at org.terracotta.exception.EntityUserException.writeReplace(EntityUserException.java:49) ~[connection-api-1.2.0-pre12.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1118) ~[na:1.8.0_121]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136) ~[na:1.8.0_121]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_121]
	at com.tc.entity.VoltronEntityAppliedResponseImpl.dehydrateValues(VoltronEntityAppliedResponseImpl.java:114) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.net.protocol.tcm.TCMessageImpl.nvToTCByteBufferArray(TCMessageImpl.java:149) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.net.protocol.tcm.TCMessageImpl.dehydrate(TCMessageImpl.java:134) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.net.protocol.tcm.TCMessageImpl.dehydrate(TCMessageImpl.java:128) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.net.protocol.tcm.TCMessageImpl.send(TCMessageImpl.java:383) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.objectserver.handler.ProcessTransactionHandler$1.handleEvent(ProcessTransactionHandler.java:109) ~[na:na]
	at com.tc.objectserver.handler.ProcessTransactionHandler$1.handleEvent(ProcessTransactionHandler.java:104) ~[na:na]
	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502) ~[client-runtime-5.2.0-pre13.jar:na]
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197) ~[client-runtime-5.2.0-pre13.jar:na]
Caused by: org.terracotta.exception.ServerSideExceptionWrapper: org.terracotta.entity.MessageCodecException: Runtime exception in deserializer
	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:387) ~[na:na]
	at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:717) ~[na:na]
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:472) ~[na:na]
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$2(ManagedEntityImpl.java:308) ~[na:na]
	at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:1025) ~[na:na]
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:173) ~[na:na]
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:164) ~[na:na]
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27) ~[na:na]
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23) ~[na:na]
	... 2 common frames omitted
Caused by: org.terracotta.exception.ServerSideExceptionWrapper: java.lang.IllegalStateException: Client 81279@127.0.0.1:Ehcache:SEFormy-cm-name-2:2b72ff6c02ff43e29246443ba635324a is either not found or not manageable
	at org.terracotta.management.service.monitoring.DefaultManagementService.lambda$sendManagementCallRequest$0(DefaultManagementService.java:105) ~[na:na]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_121]
	at org.terracotta.management.service.monitoring.DefaultManagementService.sendManagementCallRequest(DefaultManagementService.java:105) ~[na:na]
	at org.terracotta.management.entity.tms.server.ActiveTmsAgent.call(ActiveTmsAgent.java:88) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.terracotta.voltron.proxy.MethodDescriptor.invoke(MethodDescriptor.java:144) ~[management-client-5.2.0-pre15.jar:na]
	at org.terracotta.voltron.proxy.ProxyEntityMessage.invoke(ProxyEntityMessage.java:67) ~[management-client-5.2.0-pre15.jar:na]
	at org.terracotta.voltron.proxy.server.ProxyInvoker.invoke(ProxyInvoker.java:50) ~[na:na]
	at org.terracotta.voltron.proxy.server.ActiveProxiedServerEntity.invoke(ActiveProxiedServerEntity.java:53) ~[na:na]
	at org.terracotta.voltron.proxy.server.ActiveProxiedServerEntity.invoke(ActiveProxiedServerEntity.java:30) ~[na:na]
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$performAction$9(ManagedEntityImpl.java:717) ~[na:na]
	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:382) ~[na:na]
	... 10 common frames omitted
```

### PR DESCRIPTION
**Pull request by mathieucarbou**
See #279

### CODE REVIEW

File: management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java [hunk 1]
```diff
@@ -102,7 +102,7 @@ public String sendManagementCallRequest(ClientDescriptor caller, final Context c
       // handle client call
       ClientIdentifier to = ClientIdentifier.valueOf(context.get(Client.KEY));
       fullContext = context.with(topologyService.getManageableClientContext(to)
-          .orElseThrow(() -> new IllegalStateException("Client " + to + " is either not found or not manageable")));
+          .orElseThrow(() -> new IllegalArgumentException("Client " + to + " is either not found or not manageable")));
```
Comment (GaryWKeim) [inline management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java]: Are we just leaving the non-existent client in the DB?

File: voltron-proxy/voltron-proxy-client/src/main/java/org/terracotta/voltron/proxy/client/VoltronProxyInvocationHandler.java [hunk 2]
```diff
@@ -150,11 +151,20 @@ public Object invoke(final Object proxy, final Method method, final Object[] arg
...
+      return getResponse(builder.invoke().get());
     }
   }
 
+  private static Object getResponse(ProxyEntityResponse proxyEntityResponse) throws EntityUserException {
+    if (proxyEntityResponse == null) {
+      return null;
+    }
+    if (proxyEntityResponse.getMessageType() == MessageType.ERROR) {
+      throw (EntityUserException) proxyEntityResponse.getResponse();
```
Comment (GaryWKeim) [inline voltron-proxy/voltron-proxy-client/src/main/java/org/terracotta/voltron/proxy/client/VoltronProxyInvocationHandler.java]: Are you sure that's the only exception type allowed there?

File: voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyEntityResponse.java [hunk 3]
```diff
@@ -40,6 +41,10 @@ public static ProxyEntityResponse messengerResponse(Class<?> responseType, Objec
     return response(MessageType.MESSENGER, responseType, response);
   }
 
+  public static ProxyEntityResponse error(EntityUserException error) {
+    return response(MessageType.ERROR, EntityUserException.class, error);
```
Comment (GaryWKeim) [inline voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyEntityResponse.java]: Same question about the expected EntityUserException.

File: voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyMessageCodec.java [hunk 4]
```diff
@@ -186,4 +164,32 @@ public ProxyEntityMessage decodeMessage(final byte[] buffer) {
     return new ProxyEntityMessage(method, codec.decode(method.getParameterTypes(), buffer, 2, buffer.length - 2), messageType);
   }
 
+  private Class<?> getResponseType(MessageType messageType, Byte b) {
+    Map<Byte, Class<?>> mapping = reverseResponseMappings.get(messageType);
+    if (mapping == null) {
+      throw new AssertionError("WAT, no mapping for " + messageType);
```
Comment (GaryWKeim) [inline voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyMessageCodec.java]: I don't understand "WAT"

File: management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java (hunk 1 above)
Comment (mathieucarbou) [inline management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java]: I don't know what should be the behavior on your side... I guess so because it could be closed temporarily

File: voltron-proxy/voltron-proxy-client/src/main/java/org/terracotta/voltron/proxy/client/VoltronProxyInvocationHandler.java (hunk 2 above)
Comment (mathieucarbou) [inline voltron-proxy/voltron-proxy-client/src/main/java/org/terracotta/voltron/proxy/client/VoltronProxyInvocationHandler.java]: Yes! It's controlled by the Voltron proxy code. This is a wrapping exception allowing non serializable causes to still go over the network

File: voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyEntityResponse.java (hunk 3 above)
Comment (mathieucarbou) [inline voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyEntityResponse.java]: Same answer ;-)

File: voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyMessageCodec.java (hunk 4 above)
Comment (mathieucarbou) [inline voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyMessageCodec.java]: This was already there. @asnaps code ;-) if we go there anyway we'll have to crash the server since this is a very bad programmatic error

Comment (alexsnaps) [inline voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyMessageCodec.java]: Don't you f^&* around with my legacy! ;) More seriously, this should probably be a "nicer message" to the user indeed... Now, which ever way you guys go, it shall be remembered!

Comment (mathieucarbou) [inline voltron-proxy/voltron-proxy-common/src/main/java/org/terracotta/voltron/proxy/ProxyMessageCodec.java]: There's an implicit rule here: if you see a "WAT" error, you call Alex 😛

**Comment by mathieucarbou** [comment]
no more _WAT_ ;-)

File: management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java (hunk 1 above)
Comment (GaryWKeim) [inline management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java]: Start a cluster with a single client. Shutdown everything. Restart cluster without client. Are we going to leave the original client in the DB for ever?

Comment (mathieucarbou) [inline management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java]: I don't know... You have to see with @anthonydahanne because this is a use case not related to this PR...
But for example, an ehcache client could be inside a webapp. This webapp can crash or be restarted at any time. So there could be a moment where we have in our DB the information about a client that is not connected anymore.

Comment (anthonydahanne) [inline management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java]: as far as I know, whenever an event is received, the TMS reloads the topology.
so if the client is gone, the TMS will know about it.

Comment (mathieucarbou) [inline management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/DefaultManagementService.java]: @anthonydahanne : I think you speak about something else. 
This PR solves another issue: when the TMS restarts, there's a call to activate collecting stats on clients. So what if a client disconnects while the TMS was off ? The TMS don't know the new topology yet. It just sends a management call to an inexisting client.
And anyway, even if you fix the TMS, it does not remove this bug. This fix is so that validations done on server side during a client call gets reported back to the client and do not crash the server.
I don't what are the concerns here and why you speak about the TMS, it has nothing to do with this issue.
