### PR TITLE
Close #252: Missing capabilities from monitoring tree after a failover

### LINKED ISSUE #252: Missing capabilities from monitoring tree after a failover
Content of @anthonydahanne's email:

```
Salut,
Bon pas eu le temps comme prévu :-)

Alors voila ce que je te suggère : checkout master sur tc-ee, et tc platform; ouvre 2 fenêtres d’IDE
Dans TC-EE, utilise Voltron.groovy,  cree 1 nouvelle launch configuration, avec :

./tms-system-tests/src/test/resources/tc-config-ha.xml server1

Appelle la Voltron1

debugge port sur 5001 en decommentant :

        .addJvmArg("-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5001")

Demure le
Meme chose avec Voltron2 :
./tms-system-tests/src/test/resources/tc-config-ha.xml server2

Et rechange Voltorn.groovy avec :

        .addJvmArg("-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5002")


Cree 2 nouvelles debug remote config dans ton workspace tc platform, une avec 5001 et l’autre 5002

Mets les points de debug suivant :

DefaultConsumerManagementRegistry#57
AbstractTmsAgent#71 et 83
TmsAgentEntityServerService#65


Dans TC-EE demarre le TMS en debug avec terracotta://localhost:9510,localhost:9511/MyCluster comme connection (a priori tout em semblait “normal” dans le TMS, mais tu peux toujours suivre AbstractTmsCOnnection#225 pour verifier contexte / paramètres)

Tu peux démarrer 1 client. (Client.groovy avec 8 terracotta://localhost:9510,localhost:9511)

Tue le server2, le fail over va se mettre en place; observe tes points d’arrêts dans tc platform; tu remarqueras que lorsque le call est reçu, il n’y a pas de providers (donc pas de capabilities) si bien que le call sur la StatisticCollectorCapability va être marque hasExecuted==false
Tu remarqueras aussi qu’avant le fail over, tout allait bien…

Il serait intéressant de faire 1 IT dans tc platform avec 1 management call statisticcollectorcapability sur 1 nouveau actif, et faire 1 assertion comme “l’appel retourne avec succès”

Je suis pas du tout la jusque au 1er inclus -  je re travaille le mardi 3 et mercredi 4

Bon courage !
Anthony
```

### PR DESCRIPTION
**Pull request by mathieucarbou**
See #252. This PR contains:

- Workaround for https://github.com/Terracotta-OSS/terracotta-core/issues/426 (`loadExisting()` ordering issue): entities can now listen for platform events received by monitoring service to know when they can start exposing management stuff.

- Added more javadoc and more tests

- Cleaned up the code related to failover detection on entities since the platform does not send us anymore the transition steps of entities during a failover (`isActive=false` then `isActive=true`)

Note: there is also https://github.com/Terracotta-OSS/terracotta-core/issues/427 (random test failure because of bad ordering in `addNode()` call) fixed by platform team.

### CODE REVIEW

**Comment by mathieucarbou** [comment]
Also, see: https://github.com/Terracotta-OSS/terracotta-core/issues/427

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

File: management/monitoring-service-api/src/main/java/org/terracotta/management/service/monitoring/EntityEventService.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+ */
+package org.terracotta.management.service.monitoring;
+
+import com.tc.classloader.CommonComponent;
+
+/**
+ * Workaround for https://github.com/Terracotta-OSS/terracotta-core/issues/426.
+ * <p>
+ * This service allows to register a listener for platform events, to know specifically
+ * when platform tells the monitoring service that an entity has beee created.
```
Comment (GaryWKeim) [inline management/monitoring-service-api/src/main/java/org/terracotta/management/service/monitoring/EntityEventService.java]: beee -> been

File: management/monitoring-service-api/src/main/java/org/terracotta/management/service/monitoring/StatisticsService.java [hunk 2]
```diff
@@ -20,6 +20,10 @@
 import org.terracotta.management.registry.collect.StatisticCollector;
 import org.terracotta.management.registry.collect.StatisticConfiguration;
 
+/**
+ * This statistic service is injected into {@link org.terracotta.management.registry.ManagementProvider} objects implementing
+ * {@link org.terracotta.management.service.monitoring.registry.provider.MonitoringServiceAware} whe nthe yare added into a {@link ConsumerManagementRegistry}
```
Comment (GaryWKeim) [inline management/monitoring-service-api/src/main/java/org/terracotta/management/service/monitoring/StatisticsService.java]: whe nth yar -> when they are

File: management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/IStripeMonitoringPlatformListenerAdapter.java [hunk 3]
```diff
@@ -95,11 +95,11 @@ public boolean addNode(PlatformServer sender, String[] parents, String name, Ser
...
               .put(name, platformEntity);
-          // an active server is reporting a passive entity: it *can* be that a failover is occurring
-          if (!platformEntity.isActive && sender.getServerName().equals(currentActive)) {
-            delegate.serverEntityFailover(sender, platformEntity);
-          } else {
+          // Workaround for https://github.com/Terracotta-OSS/terracotta-core/issues/405
+          if (platformEntity.isActive || !sender.getServerName().equals(currentActive)) {
             delegate.serverEntityCreated(sender, platformEntity);
+          } else {
+            LOGGER.warn("Ignoring entity {}", platformEntity);
```
Comment (GaryWKeim) [inline management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/IStripeMonitoringPlatformListenerAdapter.java]: If I saw this in the logs, I wouldn't know what it means.

**Comment by mathieucarbou** [comment]
test this please
